src/controllers/UsersController.java
/*
	Created By: Donald Trowbridge
	Created: 12/18/2020
	Last Update Time:
	Last Updated by:
	Notes:
*/


package controllers;

import javax.ejb.LocalBean;
import javax.ejb.Stateless;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.ejb.EJB;
import dao.UserDAO;

import java.io.IOException;
import java.util.List;
import entities.User;

/**
 * Session Bean implementation class UsersController
 */
@Stateless
@LocalBean
@ManagedBean
@SessionScoped
public class UsersController {
	@EJB UserDAO users;
	protected User user;
	
    public List<User> getAllUsers(){
    	return users.getUsers();
    }
    
    public User getUser() {
    	return this.user;
    }
    
    public void setUser(User user) {
    	this.user = user;
    }
    
    public void editUser(User user) throws IOException {
    	setUser(user);
    	FacesContext.getCurrentInstance().getExternalContext().redirect("/cat-widgets/Admin/Profiles/EditProfile.xhtml?faces-redirect=true");
    }
  
    public void updateUser(User user) throws IOException {
    	   	users.saveUser(this.user);
	    	FacesContext.getCurrentInstance().getExternalContext().redirect("/cat-widgets/Admin/Profiles/ProfileAdmin.xhtml?faces-redirect=true");
    }
    
    public void deleteUser(User user) throws IOException {
    	users.deleteUser(user);
    	FacesContext.getCurrentInstance().getExternalContext().redirect("/cat-widgets/Admin/Profiles/ProfileAdmin.xhtml?faces-redirect=true");
    }
    
    public void cancelUpdate() throws IOException {
    	FacesContext.getCurrentInstance().getExternalContext().redirect("/cat-widgets/Admin/Profiles/ProfileAdmin.xhtml?faces-redirect=true");
    }
}

WebContent/Admin/Profiles/EditProfile.xhtml
<!-- 
	Created By: Donald Trowbridge
	Created: 12/19/2020
	Last Update Time:
	Last Updated by:
	Notes:
		-Created page to edit profiles
 -->

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head></h:head> 
<body> 
	<ui:composition template="/Layouts/commonLayout.xhtml">
		<ui:define name="title">
			<title>Edit Profile</title>
		</ui:define>
		<ui:define name="content">
			<h1>Edit Profile</h1>
			<h:form>
				<f:param name="user" value="#{usersController.user}" />
				<h:outputLabel for="UserId" value="User Id: " />
				<h:inputText value="#{usersController.user.userId}" id="UserId" readonly="true" />
				<br />
				<h:outputLabel for="FirstName" value="First Name: " />
				<h:inputText value="#{usersController.user.firstName}" id="FirstName" />
				<br />
				<h:outputLabel for="LastName" value="Last Name: " />
				<h:inputText value="#{usersController.user.lastName}" id="LastName" />
				<br />
				<h:outputLabel for="username" value="Username: " />
				<h:inputText value="#{usersController.user.username}" id="username" />
				<br />
				<h:outputLabel for="email" value="Email: " />
				<h:inputText value="#{usersController.user.email}" id="email"/>
				<br />
				<h:commandButton action="#{usersController.updateUser(usersController.user)}" value="Update" />
				<h:commandButton action="#{usersController.cancelUpdate()}" value="Cancel" />
			</h:form>
		</ui:define>
	</ui:composition>
</body> 
</html>

WebContent/Admin/Profiles/ProfileAdmin.xhtml
<!-- 
	Created By: Donald Trowbridge
	Created: 11/21/2020
	Last Update Time: 12/18/2020
	Last Updated by: Donald Trowbridge
	Notes:
		-Created as template to create shell of application and test navigation
		-12/18/2020 : Added the capability to view, delete, and edit all profiles.
 -->

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head></h:head> 
<body> 
	<ui:composition template="/Layouts/commonLayout.xhtml">
		<ui:define name="title">
			<title>Profile Admin</title>
		</ui:define>
		<ui:define name="content">
			<h1>Profile Admin</h1>
				<h:dataTable
	    			value="#{usersController.allUsers}"
	    			var="user"
	    			styleClass="product"
	    			headerClass="product-header"
	    			rowClasses="product-row-even,product-row-odd"
	    			auotUpdate="true"
	    			>
	   				<h:column>
	   					<f:facet name="header">User Id</f:facet>
	   					#{user.userId}
	   				</h:column>
	   				<h:column>
	   					<f:facet name="header">First Name</f:facet>
	   					#{user.firstName}
	   				</h:column>
	   				<h:column>
	   					<f:facet name="header">Last Name</f:facet>
	   					#{user.lastName}
	   				</h:column>
	   				<h:column>
	   					<f:facet name="header">Email</f:facet>
	   					#{user.email}
	   				</h:column>
	   				<h:column>
	   					<f:facet name="header">&nbsp;</f:facet>
	   					<h:form>
	   						<h:commandButton action="#{usersController.editUser(user)}" value="Edit" />
	   					</h:form>
	   				</h:column>
	   				<h:column>
	   					<f:facet name="header">&nbsp;</f:facet>
	   					<h:form>
	   						<h:commandButton action="#{usersController.deleteUser(user)}" value="Delete" />
	   					</h:form>
	   				</h:column>
	    		</h:dataTable>
		</ui:define>
	</ui:composition>
</body> 
</html>